version: "2"
services:

  notification:
    image: openlmis/notification
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:12-debezium
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    depends_on: [log]
    env_file: .env

  log:
    image: openlmis/rsyslog:3
    ports:
      - "514:514"
    volumes:
      - '../logs/notification-service:/var/log'
